"""Parsing tests (T004-M3): one parser per format, the independent post-parse stages, and the
registry that resolves between them.

PDF fixtures are hand-crafted minimal PDF byte strings rather than generated by a PDF-writing
library — pypdf itself is a reader/manipulator, not an author, and pulling in a dedicated PDF-writer
dependency (reportlab) purely to generate test fixtures would be test-only weight with no production
use. ``pypdf.PdfWriter.add_page`` is then used to merge single hand-crafted pages into a genuine
multi-page PDF for the OCR-fallback tests, so what is under test is this platform's own parsing code
against a PDF ``pypdf`` itself produced, not against a hand-rolled multi-page xref table.
"""

from __future__ import annotations

import io
import logging
from typing import Any

import pytest

from app.ai.core.enums import KnowledgeSourceType, PIIKind
from app.ai.core.errors import AIValidationError, ProviderError, ProviderNotConfiguredError
from app.ai.core.types import DocumentSection, RawDocument
from app.ai.parsing import checksum, classifier, language, normalizer, pii, quality
from app.ai.parsing.base import BaseDocumentParser, sections_from_headings, single_section
from app.ai.parsing.docx import DocxParser
from app.ai.parsing.html_md import HtmlParser, MarkdownParser
from app.ai.parsing.image_ocr import ImageOcrParser, is_ocr_available, ocr_text_from_bytes
from app.ai.parsing.json_parser import JsonParser
from app.ai.parsing.pdf import PdfParser
from app.ai.parsing.registry import ParserRegistry
from app.ai.parsing.text import TextParser, decode_best_effort
from app.ai.parsing.xlsx_csv import CsvParser, XlsxParser

# pypdf logs a warning for every hand-crafted fixture's deliberately minimal xref table; the fixture
# still parses correctly (asserted below), so the noise is silenced rather than fixed.
logging.getLogger("pypdf").setLevel(logging.ERROR)

TENANT = "default"


def raw(content: bytes, name: str, mime: str | None = None) -> RawDocument:
    return RawDocument(content=content, file_name=name, mime_type=mime, tenant_id=TENANT)


# ---------------------------------------------------------------------------
# PDF fixture builder — see the module docstring
# ---------------------------------------------------------------------------


def _one_page_pdf(text: str) -> bytes:
    header = (
        "%PDF-1.4\n"
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
        "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
        "3 0 obj\n<< /Type /Page /Parent 2 0 R "
        "/Resources << /Font << /F1 4 0 R >> >> "
        "/MediaBox [0 0 300 150] /Contents 5 0 R >>\nendobj\n"
        "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n"
    )
    escaped = text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
    stream = f"BT /F1 12 Tf 20 100 Td ({escaped}) Tj ET" if text else ""
    body = f"5 0 obj\n<< /Length {len(stream)} >>\nstream\n{stream}\nendstream\nendobj\n"
    trailer = (
        "xref\n0 6\n0000000000 65535 f \ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n0\n%%EOF"
    )
    return (header + body + trailer).encode("latin-1")


def multi_page_pdf(*page_texts: str) -> bytes:
    from pypdf import PdfReader, PdfWriter

    writer = PdfWriter()
    for text in page_texts:
        reader = PdfReader(io.BytesIO(_one_page_pdf(text)))
        writer.add_page(reader.pages[0])
    buffer = io.BytesIO()
    writer.write(buffer)
    return buffer.getvalue()


def _docx_bytes(headings_and_paragraphs: list[tuple[int, str, str]]) -> bytes:
    from docx import Document

    doc = Document()
    for level, heading, body in headings_and_paragraphs:
        doc.add_heading(heading, level=level)
        doc.add_paragraph(body)
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _xlsx_bytes(sheets: dict[str, list[list[Any]]]) -> bytes:
    from openpyxl import Workbook

    workbook = Workbook()
    workbook.remove(workbook.active)
    for name, rows in sheets.items():
        sheet = workbook.create_sheet(title=name)
        for row in rows:
            sheet.append(row)
    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


# ===========================================================================
# base.py
# ===========================================================================


class _StubParser(BaseDocumentParser):
    def __init__(self, *, fail: bool = False, **kwargs) -> None:
        super().__init__(name="stub", mime_types=frozenset({"text/x-stub"}),
                          extensions=frozenset({".stub"}), **kwargs)
        self._fail = fail

    def is_available(self) -> bool:
        return True

    def _parse(self, document: RawDocument):
        if self._fail:
            raise ValueError("boom")
        return "parsed", single_section("parsed")


def test_base_parser_matches_by_mime_type_first() -> None:
    parser = _StubParser()
    assert parser.can_parse(raw(b"x", "a.stub", "text/x-stub")) is True


def test_base_parser_falls_back_to_extension_when_mime_is_generic() -> None:
    parser = _StubParser()
    assert parser.can_parse(raw(b"x", "a.stub", "application/octet-stream")) is True


def test_base_parser_rejects_an_unrelated_document() -> None:
    parser = _StubParser()
    assert parser.can_parse(raw(b"x", "a.pdf", "application/pdf")) is False


def test_base_parser_enforces_the_size_ceiling() -> None:
    parser = _StubParser(max_bytes=10)
    with pytest.raises(AIValidationError, match="AI_MAX_DOCUMENT_BYTES"):
        parser.parse(raw(b"x" * 11, "a.stub"))


def test_base_parser_wraps_a_format_failure_as_provider_error() -> None:
    parser = _StubParser(fail=True)
    with pytest.raises(ProviderError, match="stub"):
        parser.parse(raw(b"x", "a.stub"))


def test_single_section_is_empty_for_blank_text() -> None:
    assert single_section("   ") == ()
    assert single_section("hello")[0].text == "hello"


def test_sections_from_headings_tracks_the_full_ancestor_chain() -> None:
    entries = [(1, "A", "a body"), (2, "B", "b body"), (3, "C", "c body"), (2, "D", "d body")]
    sections = sections_from_headings(entries)
    paths = [s.heading_path for s in sections]
    assert paths == [("A",), ("A", "B"), ("A", "B", "C"), ("A", "D")]


def test_sections_from_headings_on_no_structure_is_one_section() -> None:
    sections = sections_from_headings([(0, "", "just text, no headings")])
    assert len(sections) == 1
    assert sections[0].heading is None


# ===========================================================================
# registry.py
# ===========================================================================


def test_registry_resolves_the_first_matching_available_parser() -> None:
    registry = ParserRegistry()
    registry.register(_StubParser())
    parser = registry.resolve(raw(b"x", "a.stub"))
    assert parser.name == "stub"


def test_registry_skips_an_unavailable_parser_in_favour_of_a_later_match() -> None:
    class Unavailable(_StubParser):
        def is_available(self) -> bool:
            return False

    registry = ParserRegistry()
    registry.register(Unavailable())
    registry.register(TextParser())
    # A .stub file only the (unavailable) stub parser claims: nothing can handle it.
    with pytest.raises(Exception, match="No parser is registered"):
        registry.resolve(raw(b"x", "a.stub"))


def test_registry_raises_unsupported_document_naming_known_mime_types() -> None:
    registry = ParserRegistry()
    registry.register(TextParser())
    with pytest.raises(Exception) as caught:
        registry.resolve(raw(b"x", "a.exe", "application/x-msdownload"))
    assert "text/plain" in caught.value.details["supportedMimeTypes"]


def test_registry_rejects_re_registering_without_replace() -> None:
    registry = ParserRegistry()
    registry.register(TextParser())
    with pytest.raises(ValueError, match="already registered"):
        registry.register(TextParser())


def test_registry_describe_reports_availability_without_constructing_anything_new() -> None:
    registry = ParserRegistry()
    registry.register(TextParser())
    described = registry.describe()
    assert described[0]["name"] == "text"
    assert described[0]["available"] is True


def test_registry_names_reflects_registration_order() -> None:
    registry = ParserRegistry()
    registry.register(TextParser())
    registry.register(JsonParser())
    assert registry.names() == ("text", "json")


def test_registry_reset_clears_everything() -> None:
    registry = ParserRegistry()
    registry.register(TextParser())
    registry.reset()
    assert registry.names() == ()
    with pytest.raises(Exception, match="No parser is registered"):
        registry.resolve(raw(b"x", "a.txt", "text/plain"))


def test_register_all_registers_a_batch_in_order() -> None:
    from app.ai.parsing.registry import register_all

    registry = ParserRegistry()
    register_all(registry, [TextParser(), JsonParser()])
    assert registry.names() == ("text", "json")


def test_register_parsers_wires_the_default_composition_root() -> None:
    """The module-level singleton, as the real composition root builds it."""
    import app.ai.parsing as parsing_module

    parsing_module.parser_registry.reset()
    try:
        parsing_module.register_parsers()
        names = set(parsing_module.parser_registry.names())
        assert {"pdf", "docx", "xlsx", "html", "markdown", "csv", "json", "text"} <= names

        resolved = parsing_module.resolve_parser(raw(b"hello", "a.txt", "text/plain"))
        assert resolved.name == "text"
    finally:
        parsing_module.parser_registry.reset()


def test_resolve_parser_registers_the_default_set_on_first_use() -> None:
    import app.ai.parsing as parsing_module

    parsing_module.parser_registry.reset()
    try:
        assert parsing_module.parser_registry.names() == ()
        parsing_module.resolve_parser(raw(b"hello", "a.txt", "text/plain"))
        assert parsing_module.parser_registry.names() != ()
    finally:
        parsing_module.parser_registry.reset()


# ===========================================================================
# one fixture per supported format — Done Check item 1
# ===========================================================================


def test_text_parser() -> None:
    parser = TextParser()
    document = raw("Meal allowance is 30 EUR per day.".encode("utf-8"), "a.txt", "text/plain")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert text.strip()
    assert len(sections) == 1


def test_text_parser_decodes_cp1252_without_a_declared_charset() -> None:
    # Windows-1252 byte 0x92 is a curly right single-quote (U+2019); it is not valid UTF-8 on its
    # own, so this can only decode correctly through the cp1252 fallback.
    content = b"Employee\x92s receipt"
    text = decode_best_effort(content)
    assert "Employee" in text
    assert "’" in text
    assert "�" not in text  # no replacement characters


def test_json_parser() -> None:
    parser = JsonParser()
    document = raw(b'{"policy": {"mealAllowance": 30, "currency": "EUR"}}', "a.json")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert "policy.mealAllowance: 30" in text
    assert len(sections) == 1


def test_json_parser_rejects_invalid_json_as_a_provider_error() -> None:
    parser = JsonParser()
    with pytest.raises(ProviderError, match="invalid JSON"):
        parser.parse(raw(b"{not valid", "a.json"))


def test_json_parser_flattens_a_top_level_scalar_and_null() -> None:
    text, _ = JsonParser().parse(raw(b"null", "a.json"))
    assert text == "null"


def test_json_parser_flattens_booleans_as_lowercase() -> None:
    text, _ = JsonParser().parse(raw(b'{"active": true, "archived": false}', "a.json"))
    assert "active: true" in text
    assert "archived: false" in text


def test_json_parser_caps_recursion_depth_rather_than_recursing_unbounded() -> None:
    nested = "1"
    for _ in range(30):
        nested = f"[{nested}]"
    text, _ = JsonParser().parse(raw(nested.encode(), "a.json"))
    assert "truncated at depth" in text


def test_markdown_parser() -> None:
    parser = MarkdownParser()
    content = b"# Travel Policy\n\nIntro text.\n\n## Meals\n\nMeal allowance is 30 EUR per day.\n"
    document = raw(content, "a.md")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert text.strip()
    assert [s.heading for s in sections] == ["Travel Policy", "Meals"]
    assert sections[1].heading_path == ("Travel Policy", "Meals")


def test_markdown_parser_does_not_treat_a_hash_inside_a_fenced_code_block_as_a_heading() -> None:
    """Regression: a ``#``-prefixed line (a shell comment, a YAML/config comment) inside a fenced
    code block used to be parsed as a real ATX heading, fabricating a section boundary in the
    middle of a code sample."""
    content = (
        b"# Real Heading\n\nIntro.\n\n```bash\n# not a heading\necho hi\n```\n\n"
        b"## Second Real Heading\n\nFinal text.\n"
    )
    _, sections = MarkdownParser().parse(raw(content, "a.md"))
    assert [s.heading for s in sections] == ["Real Heading", "Second Real Heading"]
    assert "# not a heading" in sections[0].text


def test_html_parser() -> None:
    parser = HtmlParser()
    content = (
        b"<html><body><h1>Travel Policy</h1><p>Intro text.</p>"
        b"<h2>Meals</h2><p>Meal allowance is 30 EUR per day.</p>"
        b"<script>evil()</script></body></html>"
    )
    document = raw(content, "a.html", "text/html")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert "evil()" not in text
    assert [s.heading for s in sections] == ["Travel Policy", "Meals"]


def test_docx_parser() -> None:
    parser = DocxParser()
    content = _docx_bytes([
        (1, "Travel Policy", "Employees must submit receipts within 30 days."),
        (2, "Meals", "Meal allowance is 30 EUR per day."),
    ])
    document = raw(content, "a.docx")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert "Meal allowance" in text
    assert [s.heading for s in sections] == ["Travel Policy", "Meals"]
    assert sections[1].heading_path == ("Travel Policy", "Meals")


def test_docx_parser_includes_table_content() -> None:
    from docx import Document

    doc = Document()
    doc.add_heading("Rates", level=1)
    table = doc.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "Country"
    table.cell(0, 1).text = "Rate"
    table.cell(1, 0).text = "US"
    table.cell(1, 1).text = "50"
    buffer = io.BytesIO()
    doc.save(buffer)

    text, _ = DocxParser().parse(raw(buffer.getvalue(), "a.docx"))
    assert "Country" in text and "Rate" in text and "50" in text


def test_xlsx_parser() -> None:
    parser = XlsxParser()
    content = _xlsx_bytes({"Rates": [["Country", "Rate"], ["US", 50], ["DE", 45]]})
    document = raw(content, "a.xlsx")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert "Rates" in text and "US" in text and "50" in text
    assert sections[0].heading == "Rates"


def test_xlsx_parser_one_section_per_sheet() -> None:
    content = _xlsx_bytes({
        "Domestic": [["City", "Rate"], ["NY", 60]],
        "International": [["City", "Rate"], ["London", 80]],
    })
    _, sections = XlsxParser().parse(raw(content, "a.xlsx"))
    assert [s.heading for s in sections] == ["Domestic", "International"]


def test_csv_parser() -> None:
    parser = CsvParser()
    document = raw(b"name,amount\nAlice,100.00\nBob,200.00\n", "a.csv", "text/csv")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert "Alice" in text and "100.00" in text
    assert len(sections) == 1


def test_pdf_parser_text_layer() -> None:
    parser = PdfParser()
    content = multi_page_pdf("Meal allowance is 30 EUR per day.")
    document = raw(content, "a.pdf", "application/pdf")
    assert parser.can_parse(document)
    text, sections = parser.parse(document)
    assert "Meal allowance" in text
    assert sections[0].page_number == 1


def test_pdf_parser_sections_carry_page_numbers() -> None:
    content = multi_page_pdf("Page one.", "Page two.", "Page three.")
    _, sections = PdfParser().parse(raw(content, "a.pdf"))
    assert [s.page_number for s in sections] == [1, 2, 3]


def test_pdf_parser_ocr_falls_back_only_for_empty_pages(monkeypatch) -> None:
    """A mixed document: page 2 has no text layer. Only page 2 should be routed to OCR."""
    calls: list[bytes] = []

    def fake_ocr(content: bytes, *, region=None):
        calls.append(content)
        return "OCR'd scanned text"

    monkeypatch.setattr("app.ai.parsing.pdf.is_ocr_available", lambda: True)
    monkeypatch.setattr("app.ai.parsing.pdf.ocr_text_from_bytes", fake_ocr)

    content = multi_page_pdf("Page one text.", "", "Page three text.")
    text, sections = PdfParser().parse(raw(content, "a.pdf"))

    assert len(calls) == 1  # only the empty page was OCR'd
    assert "OCR'd scanned text" in text
    assert "Page one text." in text
    assert "Page three text." in text


def test_pdf_parser_ocr_failure_on_one_page_does_not_fail_the_document(monkeypatch) -> None:
    def fake_ocr(content: bytes, *, region=None):
        raise ProviderError("image_ocr", "boom")

    monkeypatch.setattr("app.ai.parsing.pdf.is_ocr_available", lambda: True)
    monkeypatch.setattr("app.ai.parsing.pdf.ocr_text_from_bytes", fake_ocr)

    content = multi_page_pdf("Page one text.", "")
    text, sections = PdfParser().parse(raw(content, "a.pdf"))

    assert "Page one text." in text
    assert len(sections) == 1  # the failed-OCR empty page contributes no section


def test_pdf_parser_respects_the_ocr_page_budget(monkeypatch) -> None:
    import app.ai.parsing.pdf as pdf_module

    monkeypatch.setattr(pdf_module, "MAX_OCR_PAGES", 1)
    monkeypatch.setattr(pdf_module, "is_ocr_available", lambda: True)
    calls: list[bytes] = []
    monkeypatch.setattr(
        pdf_module, "ocr_text_from_bytes",
        lambda content, region=None: calls.append(content) or "ocr text",
    )

    content = multi_page_pdf("", "")
    PdfParser().parse(raw(content, "a.pdf"))
    assert len(calls) == 1  # capped, even though two pages needed it


def test_pdf_parser_never_leaves_a_blank_page_as_a_fabricated_section() -> None:
    content = multi_page_pdf("Page one.", "")
    _, sections = PdfParser().parse(raw(content, "a.pdf"))
    assert len(sections) == 1
    assert sections[0].page_number == 1


def test_pdf_parser_logs_when_ocr_is_entirely_unavailable(monkeypatch) -> None:
    """Regression: an entirely-unavailable OCR path used to drop empty pages with no log line at
    all — the one degraded path in this parser that didn't log, and the most consequential one: a
    fully-scanned PDF would parse to an empty document with nothing explaining why.

    Uses a handler attached directly to the named logger rather than ``caplog``: when this test
    file runs alongside any test that touches the database, the Alembic migration those tests
    trigger calls ``logging.config.fileConfig`` with its default ``disable_existing_loggers=True``,
    which leaves every logger created before that point (module import time, here) with
    ``disabled = True`` for the rest of the session — including whenever pytest's own ``caplog``
    handler would otherwise have received the record.
    """
    monkeypatch.setattr("app.ai.parsing.pdf.is_ocr_available", lambda: False)
    content = multi_page_pdf("Page one text.", "")

    records: list[logging.LogRecord] = []

    class Collector(logging.Handler):
        def emit(self, record: logging.LogRecord) -> None:
            records.append(record)

    target = logging.getLogger("app.ai.parsing.pdf")
    handler = Collector(level=logging.WARNING)
    previous_disabled = target.disabled
    target.addHandler(handler)
    target.disabled = False
    try:
        text, sections = PdfParser().parse(raw(content, "a.pdf"))
    finally:
        target.removeHandler(handler)
        target.disabled = previous_disabled

    assert "Page one text." in text
    assert len(sections) == 1
    assert any("pdf_pages_dropped_no_ocr" in record.getMessage() for record in records)


# ===========================================================================
# image_ocr.py
# ===========================================================================


def test_is_ocr_available_never_raises() -> None:
    assert is_ocr_available() in (True, False)


def test_ocr_text_from_bytes_raises_provider_not_configured_when_unavailable(monkeypatch) -> None:
    monkeypatch.setattr("app.ai.parsing.image_ocr.is_ocr_available", lambda: False)
    with pytest.raises(ProviderNotConfiguredError, match="boto3"):
        ocr_text_from_bytes(b"fake-image-bytes")


def test_ocr_text_from_bytes_extracts_line_blocks(monkeypatch) -> None:
    class StubClient:
        def detect_document_text(self, *, Document):  # noqa: N803
            return {
                "Blocks": [
                    {"BlockType": "PAGE"},
                    {"BlockType": "LINE", "Text": "Meal allowance is 30 EUR per day."},
                    {"BlockType": "WORD", "Text": "Meal"},
                    {"BlockType": "LINE", "Text": "Approved by finance."},
                ]
            }

    monkeypatch.setattr("app.ai.parsing.image_ocr.is_ocr_available", lambda: True)

    import boto3
    monkeypatch.setattr(boto3, "client", lambda *a, **k: StubClient())

    text = ocr_text_from_bytes(b"fake-image-bytes")
    assert text == "Meal allowance is 30 EUR per day.\nApproved by finance."


def test_ocr_text_from_bytes_wraps_a_client_failure(monkeypatch) -> None:
    class ExplodingClient:
        def detect_document_text(self, *, Document):  # noqa: N803
            raise RuntimeError("throttled")

    monkeypatch.setattr("app.ai.parsing.image_ocr.is_ocr_available", lambda: True)
    import boto3
    monkeypatch.setattr(boto3, "client", lambda *a, **k: ExplodingClient())

    with pytest.raises(ProviderError, match="DetectDocumentText failed"):
        ocr_text_from_bytes(b"fake-image-bytes")


def test_image_ocr_parser_declares_its_formats() -> None:
    parser = ImageOcrParser()
    assert parser.can_parse(raw(b"x", "scan.png", "image/png"))
    assert parser.can_parse(raw(b"x", "scan.jpg"))
    assert not parser.can_parse(raw(b"x", "a.pdf", "application/pdf"))


def test_image_ocr_parser_is_available_delegates_to_the_module_function(monkeypatch) -> None:
    monkeypatch.setattr("app.ai.parsing.image_ocr.is_ocr_available", lambda: True)
    assert ImageOcrParser().is_available() is True
    monkeypatch.setattr("app.ai.parsing.image_ocr.is_ocr_available", lambda: False)
    assert ImageOcrParser().is_available() is False


def test_image_ocr_parser_parses_via_ocr_text_from_bytes(monkeypatch) -> None:
    monkeypatch.setattr(
        "app.ai.parsing.image_ocr.ocr_text_from_bytes",
        lambda content, region=None: "Meal allowance is 30 EUR per day.",
    )
    text, sections = ImageOcrParser().parse(raw(b"fake-jpeg-bytes", "scan.jpg", "image/jpeg"))
    assert text == "Meal allowance is 30 EUR per day."
    assert len(sections) == 1


def test_is_ocr_available_is_false_when_the_credential_check_itself_raises(monkeypatch) -> None:
    class ExplodingSession:
        def get_credentials(self):
            raise RuntimeError("no config file")

    import boto3
    monkeypatch.setattr(boto3, "Session", ExplodingSession)
    assert is_ocr_available() is False


# ===========================================================================
# checksum.py
# ===========================================================================


def test_checksum_is_identical_for_identical_bytes() -> None:
    """Done Check item 3: the same bytes ingested twice produce an identical checksum."""
    document_a = raw(b"identical content", "a.txt")
    document_b = raw(b"identical content", "b.txt")  # different name, same bytes
    assert checksum.checksum_for(document_a) == checksum.checksum_for(document_b)


def test_checksum_differs_for_different_bytes() -> None:
    assert checksum.checksum_for(raw(b"a", "x.txt")) != checksum.checksum_for(raw(b"b", "x.txt"))


def test_repeated_lines_finds_a_header_repeated_across_sections() -> None:
    sections = [
        DocumentSection(text="ExpenseFlow Confidential\nSection one body text here.")
        for _ in range(5)
    ]
    boilerplate = checksum.repeated_lines(sections)
    assert "ExpenseFlow Confidential" in boilerplate


def test_repeated_lines_ignores_a_line_that_only_appears_once() -> None:
    sections = [
        DocumentSection(text="ExpenseFlow Confidential\nUnique body."),
        DocumentSection(text="ExpenseFlow Confidential\nDifferent unique body."),
        DocumentSection(text="ExpenseFlow Confidential\nA third unique body."),
        DocumentSection(text="ExpenseFlow Confidential\nOne more unique body."),
        DocumentSection(text="Only in the last section, nowhere else at all."),
    ]
    boilerplate = checksum.repeated_lines(sections)
    assert "Only in the last section, nowhere else at all." not in boilerplate


def test_repeated_lines_needs_enough_sections_to_avoid_false_positives() -> None:
    sections = [DocumentSection(text="Same line\nbody") for _ in range(2)]
    assert checksum.repeated_lines(sections) == frozenset()


def test_strip_boilerplate_removes_only_matching_lines() -> None:
    text = "Header line\nReal content here.\nHeader line"
    cleaned = checksum.strip_boilerplate(text, frozenset({"Header line"}))
    assert cleaned == "Real content here."


# ===========================================================================
# normalizer.py
# ===========================================================================


def test_strip_page_numbers_removes_bare_numeric_lines() -> None:
    text = "Real content.\n12\nMore content.\nPage 13\n- 14 -"
    cleaned = normalizer.strip_page_numbers(text)
    assert "12" not in cleaned.split("\n")
    assert "Real content." in cleaned
    assert "More content." in cleaned


def test_strip_page_numbers_keeps_a_sentence_containing_a_number() -> None:
    text = "The rate is 12 EUR per day."
    assert normalizer.strip_page_numbers(text) == text


def test_clean_sections_detects_and_strips_boilerplate_across_the_document() -> None:
    sections = [
        DocumentSection(text=f"ExpenseFlow Confidential\nSection {i} unique content here.")
        for i in range(5)
    ]
    cleaned = normalizer.clean_sections(sections)
    assert all("ExpenseFlow Confidential" not in s.text for s in cleaned)
    assert all(f"Section {i} unique content" in cleaned[i].text for i in range(5))


def test_clean_sections_drops_a_section_left_empty_by_cleanup() -> None:
    sections = [DocumentSection(text="12"), DocumentSection(text="Real content.")]
    cleaned = normalizer.clean_sections(sections)
    assert len(cleaned) == 1
    assert cleaned[0].text == "Real content."


# ===========================================================================
# language.py
# ===========================================================================


def test_detect_document_language_english() -> None:
    sections = [
        DocumentSection(
            text="The employee must submit the expense claim for reimbursement within the policy."
        )
    ]
    assert language.detect_document_language(sections) == "en"


def test_detect_document_language_weights_by_section_length() -> None:
    long_english = DocumentSection(
        text=(
            "The employee shall submit the expense claim and the reimbursement policy applies "
            "to every employee for the expense in question, and the policy is clear on this."
        )
    )
    short_other = DocumentSection(text="El gasto de los empleados.")
    assert language.detect_document_language([long_english, short_other]) == "en"


def test_detect_document_language_falls_back_to_the_whole_text_when_no_section_qualifies() -> None:
    sections = [DocumentSection(text="Short.") for _ in range(3)]
    # Too short individually to vote; must not silently return the default without trying the
    # concatenation.
    result = language.detect_document_language(sections, default="unknown")
    assert result in (None, "unknown", "en")


def test_section_languages_skips_sections_below_the_minimum_length() -> None:
    sections = [DocumentSection(text="Hi")]
    assert language.section_languages(sections) == {}


# ===========================================================================
# pii.py — Done Check item 2
# ===========================================================================


def test_luhn_valid_accepts_a_known_test_card_number() -> None:
    assert pii.luhn_valid("4111111111111111")  # published Visa test number


def test_luhn_valid_rejects_an_arbitrary_digit_run() -> None:
    assert not pii.luhn_valid("1234567890123456")


def test_iban_checksum_valid_accepts_a_known_test_iban() -> None:
    assert pii.iban_checksum_valid("GB82WEST12345698765432")  # published IBAN example


def test_iban_checksum_valid_rejects_a_malformed_one() -> None:
    assert not pii.iban_checksum_valid("GB82WEST12345698765431")  # last digit altered


def test_synthetic_document_yields_exactly_the_expected_pii_kinds() -> None:
    """Done Check item 2, verbatim: a synthetic document containing an email, card number, IBAN and
    national id yields exactly those PII findings — no more, no fewer."""
    text = (
        "Please contact finance at jane.doe@example.com regarding this reimbursement.\n"
        "The corporate card on file is 4111 1111 1111 1111.\n"
        "Wire transfers should use IBAN GB82 WEST 1234 5698 7654 32.\n"
        "For tax purposes the employee's national id is 123-45-6789.\n"
        "The policy takes effect immediately and applies to all travel expenses."
    )
    findings = pii.scan(text)
    kinds = {f.kind for f in findings}
    assert kinds == {PIIKind.EMAIL, PIIKind.CREDIT_CARD, PIIKind.IBAN, PIIKind.NATIONAL_ID}
    assert len(findings) == 4


def test_pii_findings_never_expose_the_raw_matched_text() -> None:
    findings = pii.scan("Contact jane.doe@example.com for details.")
    assert findings
    assert "jane.doe@example.com" not in findings[0].sample


def test_pii_findings_do_not_overlap() -> None:
    text = "Card 4111 1111 1111 1111 and email jane.doe@example.com."
    findings = pii.scan(text)
    spans = sorted((f.start, f.end) for f in findings)
    for current, following in zip(spans, spans[1:], strict=False):
        assert current[1] <= following[0]


def test_pii_scan_on_empty_text_finds_nothing() -> None:
    assert pii.scan("") == ()


def test_pii_scan_rejects_an_unvalidated_card_like_number() -> None:
    """A 16-digit run that fails Luhn must not be reported as a credit card."""
    findings = pii.scan("Reference number: 1234 5678 9012 3456.")
    assert PIIKind.CREDIT_CARD not in {f.kind for f in findings}


def test_pii_scan_national_id_excludes_reserved_ssn_area_numbers() -> None:
    findings = pii.scan("Reference 000-12-3456 is not a real SSN.")
    assert PIIKind.NATIONAL_ID not in {f.kind for f in findings}


def test_pii_scan_bank_account_requires_context() -> None:
    """A bare long digit run is not, on its own, a bank account — see the module docstring on
    contextual kinds."""
    assert PIIKind.BANK_ACCOUNT not in {f.kind for f in pii.scan("Order number 12345678901.")}
    assert PIIKind.BANK_ACCOUNT in {
        f.kind for f in pii.scan("Please deposit to account 12345678901.")
    }


def test_pii_scan_person_name_via_title() -> None:
    findings = pii.scan("Please forward this to Mr. John Smith for approval.")
    assert PIIKind.PERSON_NAME in {f.kind for f in findings}


def test_redact_text_replaces_every_finding_with_a_typed_placeholder() -> None:
    text = "Contact jane.doe@example.com now."
    findings = pii.scan(text)
    redacted = pii.redact_text(text, findings)
    assert "jane.doe@example.com" not in redacted
    assert "[REDACTED:EMAIL]" in redacted


def test_redact_text_on_no_findings_is_unchanged() -> None:
    assert pii.redact_text("clean text", ()) == "clean text"


# ===========================================================================
# classifier.py
# ===========================================================================


def test_classify_travel_policy() -> None:
    text = " ".join(["travel policy airfare per diem mileage flight class"] * 5)
    assert classifier.classify(text) == KnowledgeSourceType.TRAVEL_POLICY


def test_classify_invoice() -> None:
    text = " ".join(["invoice number invoice date bill to payment terms amount due"] * 5)
    assert classifier.classify(text) == KnowledgeSourceType.INVOICE


def test_classify_falls_back_to_other_below_the_signal_threshold() -> None:
    assert classifier.classify("A short note about nothing in particular.") == (
        KnowledgeSourceType.OTHER
    )


def test_classify_on_empty_text_is_other() -> None:
    assert classifier.classify("") == KnowledgeSourceType.OTHER


def test_classify_is_deterministic() -> None:
    text = "travel policy airfare per diem mileage"
    assert classifier.classify(text) == classifier.classify(text)


# ===========================================================================
# quality.py — Done Check item 4
# ===========================================================================


def test_quality_score_is_bounded() -> None:
    for text in ("", "x", "a" * 5000, "\x00\x01\x02" * 100):
        assert 0.0 <= quality.score(text) <= 100.0


def test_quality_score_is_deterministic() -> None:
    text = "This is a clean, well-formed policy document with real sentences."
    assert quality.score(text) == quality.score(text)


def test_quality_score_on_empty_text_is_zero() -> None:
    assert quality.score("") == 0.0


def test_quality_score_rewards_clean_substantial_text_over_garbled_noise() -> None:
    clean = (
        "The employee travel policy sets out reimbursement rules for domestic and international "
        "travel, including per-diem rates, approved airfare classes and receipt requirements. "
        "All claims must be submitted within thirty days of the expense being incurred."
    ) * 3
    garbled = "".join(["#$%^&*()_+" if i % 2 == 0 else "x" for i in range(len(clean))])
    assert quality.score(clean) > quality.score(garbled)


def test_quality_score_penalizes_a_near_empty_extraction() -> None:
    assert quality.score("a") < quality.score("a substantial and well formed sentence" * 20)


def test_quality_breakdown_exposes_each_factor() -> None:
    breakdown = quality.score_with_breakdown("A reasonably normal sentence of text.")
    assert breakdown.score == pytest.approx(
        30 * breakdown.length_score
        + 30 * breakdown.alnum_ratio_score
        + 20 * breakdown.word_shape_score
        + 10 * breakdown.structure_score
        + 10 * breakdown.language_score,
        abs=1e-6,
    )
